controller_config:
  worker_name: controller
  job_name: controller
  calculate_type: control
  cmd:
    script-addr: ./online_workers/controller.py
    port: 20001
    host: "0.0.0.0"

tool_worker_config:
  - SplitImageIntoPatches:
      SplitImageIntoPatches_h20_1:
        calculate_type: control
        cmd:
          limit-model-concurrency: 20
          cpu-worker-threads: 8
          controller-address: http://localhost:20001
          script-addr: ./online_workers/split_image_into_patches.py
          port: 20036
          host: "0.0.0.0"
        
  - MergeBoxMask:
      MergeBoxMask_h20_1:
        calculate_type: control
        cmd:
          limit-model-concurrency: 20
          cpu-worker-threads: 8
          controller-address: http://localhost:20001
          script-addr: ./online_workers/merge_box_mask_worker.py
          port: 20037
          host: "0.0.0.0"
          iou-threshold: 0.8
          fragment-overlap-ratio: 0.2
          fragment-edge-margin-ratio: 0.03
