"""Shared VisHarness prompts and tool schemas."""

from .visual_agent import (
    COMMON_STRATEGIES,
    DATA_GENERATION_SYSTEM_PROMPT,
    PHRASE_TO_BOXMASK_PROMPT,
    PHRASE_TO_POINT_PROMPT,
    POINT_TO_BOXMASK_PROMPT,
    SPLIT_PROMPT,
    SR_PROMPT,
    SubmitFinalAnswer,
    TOOLS_LIST,
    TRAIN_TEST_SYSTEM_ABLA_PROMPT,
    TRAIN_TEST_SYSTEM_PROMPT,
    VISION_RESULT_TOOLS,
    VISION_TOOL_PROMPT,
)

__all__ = [
    "COMMON_STRATEGIES",
    "DATA_GENERATION_SYSTEM_PROMPT",
    "PHRASE_TO_BOXMASK_PROMPT",
    "PHRASE_TO_POINT_PROMPT",
    "POINT_TO_BOXMASK_PROMPT",
    "SPLIT_PROMPT",
    "SR_PROMPT",
    "SubmitFinalAnswer",
    "TOOLS_LIST",
    "TRAIN_TEST_SYSTEM_ABLA_PROMPT",
    "TRAIN_TEST_SYSTEM_PROMPT",
    "VISION_RESULT_TOOLS",
    "VISION_TOOL_PROMPT",
]
